export const slider_items = [
    {
        id: 1,
        img: "images/pngs/female-model_01.png",
        title: "FASHION NOVA",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et ab id a doloribus quas numquam laborum, nobis optio fugiat maiores",
        background: "DCEED1",
    },
    {
        id: 2,
        img: "images/pngs/model_10.png",
        title: "VARIETY LOOKS",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et ab id a doloribus quas numquam laborum, nobis optio fugiat maiores",
        background: "CED4DA",
    },
    {
        id: 3,
        img: "images/pngs/female-model_05.png",
        title: "JUICY COUTURE",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et ab id a doloribus quas numquam laborum, nobis optio fugiat maiores",
        background: "FCf1ED",
    },
    {
        id: 4,
        img: "images/pngs/female-model_06.png",
        title: "EIGHTIES MAKEOVER",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Et ab id a doloribus quas numquam laborum, nobis optio fugiat maiores",
        background: "C6E2E9"
    }
]

export const categories = [
    {
        id: 1,
        img: "images/categories/category_02.jpg",
        title: "BASICS",
    },
    {
        id: 2,
        img: "images/categories/category_10.jpg",
        title: "CLASSY",
    },
    {
        id: 3,
        img: "images/categories/category_05.jpg",
        title: "TRENDS",
    },
    {
        id: 4,
        img: "images/categories/category_03.jpg",
        title: "STREET"
    }   
]

export const popular_products = [
    {
        id: 1,
        title: "Brazalete Big Vibes",
        img: "images/products/accesories/accesory_05.png",
        product: "accesory",
        brand: "ISADORA",
        collection: "Trends",
        price: "3,599",
    },
    {
        id: 2,
        title: "Chaqueta Biker",
        img: "images/products/bikers/biker_01.png",
        product: "biker",
        brand: "GIORGIO ARMANI",
        collection: "Basics",
        price: "18,727",
    },
    {
        id: 3,
        title: "Conjunto Lady Creme",
        img: "images/products/coats/coat_03.png",
        product: "coat",
        brand: "CHRISTIAN DIOR",
        collection: "Classy",
        price: "98,956",
    },
    {
        id: 4,
        title: "Zapatos Classic One",
        img: "images/products/heels/heels_06.png",
        product: "heels",
        brand: "CHRISTIAN LOUBOUTIN",
        collection: "Classy",
        price: "48,099",
    },
    {
        id: 5,
        title: "Campera Outwear",
        img: "images/products/jackets/jacket_16.png",
        product: "jacket",
        brand: "RIP CURL",
        collection: "Street",
        price: "32,420",
    },
    {
        id: 6,
        title: "Campera Winter-Puff",
        img: "images/products/puffers/puffer_05.png",
        product: "puffer",
        brand: "THE NORTH FACE",
        collection: "Street",
        price: "43,650",
    },
    {
        id: 7,
        title: "Bolso Dior",
        img: "images/products/purses/purse_12.png",
        product: "purse",
        brand: "CHRISTIAN DIOR",
        collection: "Trends",
        price: "62,299",
    },
    {
        id: 8,
        title: "Blusa Stripes",
        img: "images/products/shirts/shirt_03.png",
        product: "shirt",
        brand: "ISADORA",
        collection: "Street",
        price: "6,580",
    },
    {
        id: 9,
        title: "Buzo Canguro Blank",
        img: "images/products/sweatshirts/sweatshirt_03.png",
        product: "sweatshirt",
        brand: "NIKE",
        collection: "Basics",
        price: "12,080",
    },
    {
        id: 10,
        title: "Rolex Gold",
        img: "images/products/watches/watch_03.png",
        product: "watch",
        brand: "ISADORA",
        collection: "Basics",
        price: "38,999",
    },
    {
        id: 11,
        title: "Traje Navy Blue",
        img: "images/products/suits/suit_05.png",
        product: "suit",
        brand: "GIORGIO ARMANI",
        collection: "Classy",
        price: "90,200",
    },
    {
        id: 12,
        title: "Zapatos Classic Men",
        img: "images/products/shoes/shoes_02.png",
        product: "shoes",
        brand: "CHRISTIAN LOUBOUTIN",
        collection: "Trends",
        price: "64,375",
    },
    {
        id: 13,
        title: "Remera Básica",
        img: "images/products/tshirts/tshirt_01.png",
        product: "tshirt",
        brand: "TOMMY HILFIGER",
        collection: "Classy",
        price: "8,550",
    },
    {
        id: 14,
        title: "Gorra Blank",
        img: "images/products/caps/cap_01.png",
        product: "cap",
        brand: "NIKE",
        collection: "Basics",
        price: "4,860",
    },
    {
        id: 15,
        title: "Bolso All Stars",
        img: "images/products/bags/bag_01.png",
        product: "bag",
        brand: "LOUIS VUITTON",
        collection: "Classy",
        price: "285,999",
    },
    {
        id: 16,
        title: "Victoria's Nightdress",
        img: "images/products/nightdresses/nightdress_01.png",
        product: "nightdress",
        brand: "VICTORIA'S SECRET",
        collection: "none",
        price: "96,285"
    }
]